[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."score-jobs"]
  timeout = 26

[functions."fetch-jobs"]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
